{% set name = "rq" %}
{% set version = "1.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f680c52c7079266465d5e5c49679fab0d14db11d70fec6f1470423408b6bbcf6

build:
  number: 0
  noarch: python
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '
  entry_points:
    - rq = rq.cli:main
    - rqinfo = rq.cli:info
    - rqworker = rq.cli:worker

requirements:
  host:
    - python
    - pip

  run:
    - python
    - setuptools
    - redis-py >=3.0.0
    - click >=5.0

test:
  imports:
    - rq
    - rq.cli
    - rq.compat
    - rq.contrib
  commands:
    - rq --help
    - rqinfo --help
    - rqworker --help

about:
  home: https://python-rq.org/
  license: BSD 2-Clause
  license_file: {{ environ["RECIPE_DIR"] }}/LICENSE
  license_family: BSD
  summary: RQ is a simple, lightweight, library for creating background jobs, and processing them.
  doc_url: https://python-rq.org/docs/
  dev_url: https://github.com/rq/rq

extra:
  recipe-maintainers:
    - kwilcox
    - daf
    - jkornblum
