{% set name = "rq" %}
{% set version = "1.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0291603f0c5bb0ef18363f6b325ae76076c1d79bb918e052aac1f8da2297dbfb

build:
  number: 0
  noarch: python
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '
  entry_points:
    - rq = rq.cli:main
    - rqinfo = rq.cli:info
    - rqworker = rq.cli:worker

requirements:
  host:
    - python >=3.6
    - pip

  run:
    - python >=3.6
    - setuptools
    - redis-py >=3.0.0
    - click >=5.0

test:
  imports:
    - rq
    - rq.cli
    - rq.compat
    - rq.contrib
  commands:
    - rq --help
    - rqinfo --help
    - rqworker --help

about:
  home: https://python-rq.org/
  license: BSD-2-Clause
  license_file: LICENSE
  license_family: BSD
  summary: RQ is a simple, lightweight, library for creating background jobs, and processing them.
  doc_url: https://python-rq.org/docs/
  dev_url: https://github.com/rq/rq

extra:
  recipe-maintainers:
    - kwilcox
    - daf
    - jkornblum
    - wolfv
