{% set name = "rq" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/rq-{{ version }}.tar.gz
  sha256: 76d2a4a27f8fd5c4cfa200cd442efe3c1fd73525c676af06f07fcc0b81bdb70d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - rq = rq.cli:main
    - rqinfo = rq.cli:info
    - rqworker = rq.cli:worker

requirements:
  host:
    - python >=3.6
    - pip
    - hatchling
  run:
    - python >=3.6
    - redis-py >=4.0.0
    - click >=5.0.0
    - hatchling

test:
  imports:
    - rq
    - rq.cli
    - rq.contrib
  commands:
    - rq --help
    - rqinfo --help
    - rqworker --help

about:
  home: https://python-rq.org/
  license: BSD-2-Clause
  license_file: LICENSE
  license_family: BSD
  summary: RQ is a simple, lightweight, library for creating background jobs, and processing them.
  doc_url: https://python-rq.org/docs/
  dev_url: https://github.com/rq/rq

extra:
  recipe-maintainers:
    - kwilcox
    - daf
    - jkornblum
    - wolfv
    - MichelML
