schema_version: 1

context:
  name: rq
  version: 2.6.1

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/rq-${{ version }}.tar.gz
  sha256: db5c0d125ac9dbd4438f9a5225ea3e64050542b416fd791d424e2ab5b2853289

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - rq = rq.cli:main
      - rqinfo = rq.cli:info
      - rqworker = rq.cli:worker

requirements:
  host:
    - python >=3.9
    - pip
    - hatchling
  run:
    - python >=3.9
    - croniter
    - redis-py >=3.5,!=6
    - click >=5

tests:
  - python:
      imports:
        - rq
      pip_check: true
  - requirements:
      run:
        - pip
    script:
      - rq --help
      - rqinfo --help
      - rqworker --help

about:
  homepage: https://python-rq.org/
  license: BSD-2-Clause
  license_file: LICENSE
  summary: RQ is a simple, lightweight, library for creating background jobs, and processing them.
  documentation: https://python-rq.org/docs/
  repository: https://github.com/rq/rq

extra:
  recipe-maintainers:
    - kwilcox
    - daf
    - jkornblum
    - wolfv
    - MichelML
